### ISSUE TITLE
Practice splits have wrong labels

### ISSUE THREAD

**Issue by TudorAndrei** [Perez-AlmendrosC/dontpatronizeme#4]
As it can be seen in the photo, for the same `par_id`, the labels are different. On the left is the dataset, and on the right is the practice split.

![2022-01-06-114109_1358x262_scrot](https://user-images.githubusercontent.com/25133006/148373434-f599a2dc-6384-4c86-bd46-1b8f29c4baec.png)
o

**Comment by luisespinosaanke** [comment]
Hi,

Thanks for your interest in the task and for reporting this. How do you load the dataset in the left screenshot? It might be that you are using an older version of the manager we provide. We added in november a modification to the label dictionary ([here](https://github.com/Perez-AlmendrosC/dontpatronizeme/blob/5fdc7b8d3c7988a7a12505a1b0a33d634f29833d/semeval-2022/dont_patronize_me.py#L53)), where we hardcoded the categories ('unbalanced power relations' in position 0, 'shallow solution' to 1, etc), to make it clear which category corresponds to which position in the multilabel array.

Hope this is helpful, but don't hesitate to request further clarifications if needed!

Luis

**Comment by TudorAndrei** [comment]
I was using an older version of the manager. Thinks are working now. Thank you
